server:
  env: dev
  host: 0.0.0.0
  port: 8888

database:
  host: localhost
  user: root
  pass: pass
  db_name: vc_backend

redis:
  host: localhost
  port: 6379
  pass: null

vector:
  host: localhost
  api_key: ""

scylla:
  host: localhost
  user: scylla
  pass: scylla

llm:
  base_url: http://localhost:11434
  model: qwen2
  timeout: 30
  max_tokens: 2048

text_embedding:
  base_url: http://localhost:11434

browser:
  url: http://localhost:9222
